project_name: memos
dist: build/backend
builds:
  - dir: ./memos-upstream
    main: ./bin/memos
    binary: memos
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - ppc64le
      - riscv64
      - s390x
    goarm:
      - "5"
      - "6"
      - "7"
    goamd64:
      - v1
      - v2
      - v3
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: "386"
    flags: >-
      -trimpath
    ldflags: >-
      -s
      -w
      -X main.Date={{.CommitDate}}
      -X github.com/usememos/memos/server/version.Version={{ trimprefix .Version "v" }}
      -X github.com/usememos/memos/server/version.DevVersion={{ trimprefix .Version "v" }}
    mod_timestamp: "{{ .CommitTimestamp }}"

upx:
  - enabled: true
    goos: [linux]
    goarch: [arm, arm64, "386", amd64, ppc64le]
    compress: "best"
    lzma: true

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}-{{ .Tag }}-{{- .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}l{{ end -}}
      {{- if .Amd64 }}{{- if ne .Amd64  "v1" }}_{{ .Amd64 }}{{ end -}}{{ end -}}
    builds_info:
      group: root
      owner: root
      mode: 0644
    format_overrides:
      - goos: windows
        format: zip
    files:
      # add front-end to compressed archives
      - src: build/frontend/dist/
        dst: dist

checksum:
  disable: false
  name_template: "{{ .ProjectName }}-{{ .Tag }}_SHA256SUMS.txt"
  algorithm: sha256

snapshot:
  # Default is `{{ .Version }}-SNAPSHOT-{{.ShortCommit}}`.
  name_template: "{{ incpatch .Version }}-dev"

#! Due to Goreleaser OSS limitations for nightly builds, GitHub release is created via GH Actions. *
