#* These settings are intended to create local Docker test builds with `task build:testing:docker`.

project_name: memos
dist: build/backend
builds:
  - dir: ./memos-upstream
    main: ./bin/memos
    binary: memos
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    targets:
      - linux_386
      - linux_amd64
      - linux_amd64_v2
      - linux_amd64_v3
      - linux_arm_5
      - linux_arm_6
      - linux_arm_7
      - linux_arm64
      - linux_ppc64le
      - linux_riscv64
      - linux_s390x
    flags: >-
      -trimpath
    ldflags: >-
      -s
      -w
      -X main.Date={{.CommitDate}}
      -X github.com/usememos/memos/server/version.Version={{ trimprefix .Version "v" }}
      -X github.com/usememos/memos/server/version.DevVersion={{ trimprefix .Version "v" }}
    mod_timestamp: "{{ .CommitTimestamp }}"

upx:
  - enabled: false
    goos: [linux]
    goarch: [arm, arm64, "386", amd64, ppc64le]
    compress: "best"
    lzma: true

archives:
  - format: binary

checksum:
  disable: true

snapshot:
  name_template: "{{ incpatch .Version }}-dev"


