# https://goreleaser.com

project_name: memos
dist: build/backend
builds:
  - dir: ./memos-upstream
    main: ./bin/memos
    binary: memos
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    goamd64:
      - v1
    ignore:
      - goos: windows
        goarch: arm64
      - goos: linux
        goarch: arm64
    flags: >-
      -trimpath
    ldflags: >-
      -s
      -w
      -X main.Date={{.CommitDate}}
      -X github.com/usememos/memos/server/version.Version={{ trimprefix .Version "v" }}
      -X github.com/usememos/memos/server/version.DevVersion={{ trimprefix .Version "v" }}
    mod_timestamp: "{{ .CommitTimestamp }}"

upx:
  - enabled: true
    goos: [linux, windows]
    goarch: [arm, arm64, "386", amd64, ppc64le]
    compress: "best"
    lzma: true

changelog:
  skip: true

snapshot:
  name_template: "{{ incpatch .Version }}-dev"
