# https://taskfile.dev

# To use this Taskfile on Windows, add Git\bin (or git\usr\bin) to PATH.
# This allows using Git's sh.exe to run posix shell commands.
#
# To add git to the path just for the current powershell session:
#* $Env:Path += ";$Env:ProgramFiles\Git\bin";
#

version: "3"

tasks:
  postbuild:restoreplaceholder:
    desc: Restore front-end placeholder
    cmds:
      - sh -c "rm -rf ./memos-upstream/server/dist"
      - sh -c "mv -f ./memos-upstream/server/dist.bak ./memos-upstream/server/dist"
  build:
    desc: Build binaries for current OS/Arch
    cmds:
      - goreleaser build --clean --single-target
      - task: postbuild:restoreplaceholder

  build:all:
    desc: Build binaries for all OS/Arch
    cmds:
      - goreleaser build --clean
      - task: postbuild:restoreplaceholder

  build:snapshot:
    desc: Build binaries for current OS/Arch, ignores git status
    cmds:
      - goreleaser build --snapshot --clean --single-target
      - task: postbuild:restoreplaceholder

  build:snapshot:all:
    desc: Build binaries for all OS/Arch, ignores git status
    cmds:
      - goreleaser build --snapshot --clean
      - task: postbuild:restoreplaceholder

  clean:
    desc: Cleanup build artifacts
    ignore_error: true
    cmds:
      - sh -c "rm -rf ./build"
      - sh -c "rm -rf ./memos-upstream/web/node_modules"
      - sh -c "rm -rf ./memos-upstream/web/dist"
      - sh -c "rm -rf ./memos-upstream/server/dist"
      - sh -c "mv -f ./memos-upstream/server/dist.bak ./memos-upstream/server/dist"

  resetsubtree:
    desc: |
      Reset subtree to a tag.
      Usage: `task setup-subtree -- v0.0.0` to setup a specific tag.
    cmds:
      - sh -c "rm -rf ./memos-upstream || true"
      - git rm -fr memos-upstream --ignore-unmatch
      - git commit -m "Remove memos-upstream subtree"
      - git subtree add --prefix=memos-upstream https://github.com/usememos/memos.git main --squash

  pushbuild:
    desc: |
      Checkout subtree to supplied tag and push a new tag to origin.
      Usage: `task checkout-upstream -- v0.0.0` to checkout a specific tag.
    cmds:
      - git subtree pull --prefix=memos-upstream https://github.com/usememos/memos.git tags/{{.CLI_ARGS}} --squash --message="Checkout memos-upstream to {{.CLI_ARGS}}"
      - git push origin
      - git tag -a {{.CLI_ARGS}} -m "Push {{.CLI_ARGS}}"
      - git push origin {{.CLI_ARGS}}
